### ISSUE TITLE
Testes Automatizados do CRUD de Usuário

### ISSUE THREAD

**Issue by Polibits** [Polibits/Gaga_Insano_Backend#7]
Criar primeira rotina de testes automatizados, para testar as funcionalidade da API relativas aos usuários. Ela deve testar todo o CRUD de usuários do sistema, cobrindo todos os principais casos possíveis. Por exemplo:
- Cadastro de usuário válido
- Tentativa de cadastro de usuário inválido
- Atualização de dados do usuário
- Autenticação de credenciais

**Comment by henriqueedu2001** [comment]
testes feitos
